Updated ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -38,6 +38,20 @@ jobs:
           done
           sleep 5
 
+      - name: Attendre MongoDB
+        run: |
+          timeout=60
+          until docker exec mysql mysqladmin ping -h localhost -u root -proot --silent; do
+            echo "Waiting for MongoDB..."
+            sleep 3
+            timeout=$((timeout - 3))
+            if [ $timeout -le 0 ]; then
+              echo "MongoDB failed to start"
+              exit 1
+            fi
+          done
+          sleep 5
+
       - name: Éxécuter les tests (TODO - ajouter test_products)
         run: docker exec store_manager_cli pytest ./src/tests/test_user.py
 
